### ISSUE TITLE
Create django-admin POC

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/sckan-composer#7]
Update django-admin change page to something closer to: 
![Image](https://user-images.githubusercontent.com/19196034/199038909-15e1843f-6eaa-469f-827b-ddf382ef6d5e.png)

- [x] [Add infrastructure skeleton](https://github.com/MetaCell/sckan-composer/issues/1) 
- [x] [Add basic model](https://github.com/MetaCell/sckan-composer/issues/8)
- [x] [Update django change template to display data as requested in the wireframe](https://github.com/MetaCell/sckan-composer/issues/9)
- [x] [Customize autocomplete fields requests ](https://github.com/MetaCell/sckan-composer/issues/2)
